config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { registrations: 'registrations' }

  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
    post 'users/' => 'users#create', :as => 'user'
  end

  resources :products
  resources :shopping_carts, only: [:index, :show, :new, :update] do
    delete 'product/:product_id', to: 'shopping_carts#destroy', as: 'destroy'
    collection do
      post :search
    end
  end
  get '/', to: 'products#index'
end

app/controllers/shopping_carts_controller.rb
class ShoppingCartsController < ApplicationController
  before_action :set_orders, only: %i[show update]
  before_action :set_order_products, only: %i[destroy]
  before_action :find_by_product, only: %i[search]

  def index
    order_list
  end

  def search

    if params[:search_term].present?
      if @product.present?
        save_order unless order_list
        save_order_product unless order_product_exist?
      end
    end
    respond_to do |format|
      redirect_order(format)
    end
  end

  def show; end

  def update
    respond_to do |format|
      if @order.update(status: 'confirm')
        redirect_order(format)
      else
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @order_products.destroy
    respond_to do |format|
      format.html { redirect_to shopping_carts_path }
      format.json { head :no_content }
    end
  end

  private

  def set_order_products
    @order_products = OrderProduct.find_by(
      order_id: params[:shopping_cart_id],
      product_id: params[:product_id]
    )
  end

  def set_orders
    @order = Order.find(params[:id])
  end

  def find_by_product
    @product = Product.find_by(code: params[:search_term])
  end

  def save_order_product
    OrderProduct.create(
      order_id: @orders.id,
      product_id: @product.id,
      quantity: 1
    )
  end

  def save_order
    @orders = Order.new(
      status: :waiting,
      user_id: current_user.id
    )
    @orders.save
  end

  def order_list
    @orders ||= Order.find_by(user_id: current_user.id, status: 'waiting')
    @orders.total = @orders.order_products.collect { |order_prod| order_prod.valid? ? order_prod.unit_price * order_prod.quantity : 0}.sum unless @orders.nil?
  end

  def order_product_exist?
    order_product = OrderProduct.find_by(order_id: @orders.id, product_id: @product.id)
    order_product.update(quantity: order_product.quantity + 1) unless order_product.nil?
  end

  def redirect_order(format)
    format.html do
      redirect_to shopping_carts_path
    end
    format.json { render :show, status: :ok, location: @orders }
  end
end

app/views/shopping_carts/_form.html.erb
<%= form_with(url: search_shopping_carts_path, data: { controller: 'form-submission', form_submission_target: "form" })do | form | %>
    <div class="relative mx-4 lg:mx-0 py-3">
        <span class="absolute inset-y-0 left-0 pl-3 flex items-center">
            <svg class="h-5 w-5 text-gray-500" viewBox="0 0 24 24" fill="none">
                <path
                    d="M21 21L15 15M17 10C17 13.866 13.866 17 10 17C6.13401 17 3 13.866 3 10C3 6.13401 6.13401 3 10 3C13.866 3 17 6.13401 17 10Z"
                    stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
                </path>
            </svg>
        </span>

        <%= form.text_field 'search_term',
            placeholder: 'Scan product items...',
            class:"w-2/4 ml-2 pl-8 pr-4 h-10 border rounded px-4 bg-blue-50 focus:outline-none focus:ring-2 focus:ring-blue-600 focus:border-transparent"
        %>

        <%= form.submit 'Add',
            class:"border border-blue-800 text-blue-800 rounded-md px-4 py-2 m-2 transition duration-800 ease select-none hover:text-white hover:bg-blue-600 focus:outline-none focus:shadow-outline",
            data: { action: "input->form-submission#search" }
        %>
    </div>
<% end %>

app/views/shopping_carts/_order.html.erb
<% if @orders %>
    <%= turbo_frame_tag dom_id(orders) do %>
        <% if @orders.order_products.empty? %>
            <div align="center"><em>No matching products</em></div>
        <% end %>
        <% @orders.order_products.map do |order| %>
            <div class="flex border-b border-gray-200 hover:bg-gray-100">
                <div class="w-1/2 px-2 py-3 whitespace-no-wrap border-b border-gray-200">
                    <div class="flex items-center">
                        <div class="ml-4">
                            <div class="text-sm leading-5 font-medium text-gray-900">
                                <%= order.product.id %>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="w-1/2 px-6 py-3 whitespace-no-wrap border-b border-gray-200">
                    <div class="text-sm leading-5 text-gray-900"><%= order.product.code %></div>
                </div>

                <div class="w-1/2 px-6 py-3 whitespace-no-wrap border-b border-gray-200">
                    <div class="text-sm leading-5 text-gray-900"><%= order.product.description %></div>
                </div>

                <div class="w-1/2 px-6 py-3 whitespace-no-wrap border-b border-gray-200 text-sm leading-5 text-gray-500">
                     <%= sprintf('%.2f', order.product.price) %>
                </div>

                <div class="w-1/2 px-6 py-3 whitespace-no-wrap border-b border-gray-200">
                    <%=  order.quantity %>
                </div>

                <div class="w-1/2 px-6 py-3 whitespace-no-wrap border-b border-gray-200">
                    <div class="text-sm leading-5 text-gray-900">
                        <%= button_to :delete, shopping_cart_destroy_path(shopping_cart_id: order.order_id, product_id: order.product.id), method: :delete, class:"bg-red-500 text-white active:bg-purple-600 font-bold uppercase text-xs px-4 py-2 rounded shadow hover:shadow-md outline-none focus:outline-none mr-1 mb-1 ease-linear transition-all duration-150", data: {confirm: 'Are you sure?'} %>
                    </div>
                </div>
            </div>
        <% end %>
            <div class="flex border-b border-gray-200 hover:bg-gray-100">
                <div class="w-1/2 py-3 px-6 text-left whitespace-nowrap">
                    <div class="flex items-center">
                        <div class="font-sans text-2xl font-bold pl-3 py-3">
                            TOTAL R$ <%= @orders.total %>
                        </div>
                    </div>
                </div>
            </div>

            <div class="flex justify-center px-5 mb-2 text-sm">
                <%= button_to "Finish", shopping_cart_path(id:  @orders.id), method: :put, class:"border border-blue-800 text-blue-800 rounded-md px-4 py-2 m-2 transition duration-800 ease select-none hover:text-white hover:bg-blue-600 focus:outline-none focus:shadow-outline" %>
            </div>
    <% end %>
<% else %>
    <div align="center"><em>No matching products</em></div>
<% end %>

app/views/shopping_carts/index.html.erb
<%= turbo_stream_from :shoppingCartList %>
<div class=" flex  flex-col  md:flex-row justify-center  flex-wrap gap-6 mt-10">
    <div class="w-3/5">
        <div class="bg-white shadow-lg mx-auto border-b-4 border-indigo-800 rounded-2xl overflow-hidden  hover:shadow-2xl transition duration-500 transform hover:scale-105 cursor-pointer" >
            <div class="bg-indigo-800  flex h-20 p-4 items-center">
                <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5 text-white" viewBox="0 0 20 20" fill="currentColor">
                    <path fill-rule="evenodd" d="M17.707 9.293a1 1 0 010 1.414l-7 7a1 1 0 01-1.414 0l-7-7A.997.997 0 012 10V5a3 3 0 013-3h5c.256 0 .512.098.707.293l7 7zM5 6a1 1 0 100-2 1 1 0 000 2z" clip-rule="evenodd" />
                </svg>
                <p class="ml-4 text-white uppercase">Product List</p>
            </div>
            <%= render 'form' %>
        </div>
    </div>
    <div class="w-3/5">
        <div class="bg-white shadow-lg mx-auto border-b-4 border-indigo-800 rounded-2xl overflow-hidden  hover:shadow-2xl transition duration-500 transform hover:scale-105 cursor-pointer" >
            <div class="bg-indigo-800  flex h-20 p-4 items-center">
                <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5 text-white" viewBox="0 0 20 20" fill="currentColor">
                    <path d="M3 1a1 1 0 000 2h1.22l.305 1.222a.997.997 0 00.01.042l1.358 5.43-.893.892C3.74 11.846 4.632 14 6.414 14H15a1 1 0 000-2H6.414l1-1H14a1 1 0 00.894-.553l3-6A1 1 0 0017 3H6.28l-.31-1.243A1 1 0 005 1H3zM16 16.5a1.5 1.5 0 11-3 0 1.5 1.5 0 013 0zM6.5 18a1.5 1.5 0 100-3 1.5 1.5 0 000 3z" />
                </svg>
                <p class="ml-4 text-white uppercase">Market List</p>
            </div>
            <div class="min-w-max w-full table-auto">
                <div>
                    <div class="flex bg-gray-200 text-gray-600 uppercase text-sm leading-normal">
                        <div class="w-1/2 py-3 px-2 text-left">Id</div>
                        <div class="w-1/2 py-3 px-6 text-left">Code</div>
                        <div class="w-1/2 py-3 px-6 text-left">Description</div>
                        <div class="w-1/2 py-3 px-6 text-left">Price</div>
                        <div class="w-1/2 py-3 px-6 text-left">Qtde</div>
                        <div class="w-1/2 py-3 px-6 text-left">Actions</div>
                    </div>
                </div>
                <%= turbo_frame_tag :shoppingCartList do %>
                    <%= render 'order', orders: @orders %>
                <% end %>
            </div>
        </div>
    </div>
</div>

app/views/shopping_carts/show.html.erb
asdsad
<%= turbo_frame_tag dom_id(@orders) do %>
    <% if @orders.order_products.empty? %>
        <div align="center"><em>No matching products</em></div>
    <% end %>
    <% @orders.order_products.map do |order| %>
        <div class="flex border-b border-gray-200 hover:bg-gray-100">
            <div class="w-1/2 px-2 py-3 whitespace-no-wrap border-b border-gray-200">
                <div class="flex items-center">
                    <div class="ml-4">
                        <div class="text-sm leading-5 font-medium text-gray-900">
                            <%= order.product.id %>
                        </div>
                    </div>
                </div>
            </div>

            <div class="w-1/2 px-6 py-3 whitespace-no-wrap border-b border-gray-200">
                <div class="text-sm leading-5 text-gray-900"><%= order.product.code %>223423</div>
            </div>

            <div class="w-1/2 px-6 py-3 whitespace-no-wrap border-b border-gray-200">
                <div class="text-sm leading-5 text-gray-900"><%= order.product.description %></div>
            </div>

            <div class="w-1/2 px-6 py-3 whitespace-no-wrap border-b border-gray-200 text-sm leading-5 text-gray-500">
                <%=  order.product.price %>
            </div>

            <div class="w-1/2 px-6 py-3 whitespace-no-wrap border-b border-gray-200">
                <%=  order.quantity %>
            </div>

            <div class="w-1/2 px-6 py-3 whitespace-no-wrap border-b border-gray-200">
                <div class="text-sm leading-5 text-gray-900">
                    <%= button_to :delete, shopping_cart_destroy_path(shopping_cart_id: order.order_id, product_id: order.product.id), method: :delete, class:"bg-red-500 text-white active:bg-purple-600 font-bold uppercase text-xs px-4 py-2 rounded shadow hover:shadow-md outline-none focus:outline-none mr-1 mb-1 ease-linear transition-all duration-150", data: {confirm: 'Are you sure?'} %>
                </div>
            </div>
        </div>
    <% end %>
<% end %>