config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { registrations: 'registrations' }

  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
    post 'users/' => 'users#create', :as => 'user'
  end

  resources :products
  resources :shopping_carts, only: [:index, :show, :new, :update] do
    delete 'product/:product_id', to: 'shopping_carts#destroy', as: 'destroy'
    collection do
      post :search
    end
  end
  get '/', to: 'products#index'
end

app/models/product.rb
class Product < ApplicationRecord
  after_create_commit { broadcast_prepend_to :products }
  after_update_commit { broadcast_replace_to :products }
  after_destroy_commit { broadcast_remove_to :products }

  belongs_to :category, optional: true
  has_many :order_products

  validates :description, presence: true
  validates :price, presence: true

  enum status: { active: 1, inactive: 0 }
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_products, only: %i[show edit update destroy]
  before_action :new_product, only: %i[index create]

  def index
    @products = Product.all.order(id: :desc)
  end

  def edit; end

  def create
    attributes_params
    respond_to do |format|
      if save_product
        redirect_product(format)
      else
        format_turbo(format)
        product_errors(format)
      end
    end
  end

  def update
    attributes_params
    respond_to do |format|
      if save_product
        redirect_product(format)
      else
        format_turbo(format)
        product_errors(format)
      end
    end
  end

  def show; end

  def destroy
    @product.destroy
    respond_to do |format|
      redirect_product(format)
      format.json { head :no_content }
    end
  end

  private

  def save_product
    @product.save
  end

  def new_product
    @product = Product.new
  end

  def alert_errors
    redirect_to products_path	, alert: @product.errors.full_messages.to_sentence
  end

  def set_products
    @product = Product.find(params[:id])
  end

  def redirect_product(format)
    format.html do
      redirect_to products_path
    end
    format.json { render :show, status: :ok, location: @product }
  end

  def format_turbo(format)
    format.turbo_stream do
      render turbo_stream: turbo_stream.replace(
        @product, partial: 'products/form', locals: { product: @product }
      )
    end
    format.html { render :new, status: :unprocessable_entity }
  end

  def product_errors(format)
    format.html { render :edit, status: :unprocessable_entity }
    format.json { render json: @product.errors, status: :unprocessable_entity }
  end

  def attributes_params
    @product.attributes = products_params
  end

  def products_params
    params.require(:product).permit(:code, :description,
      :price, :category_id, :status)
  end
end

app/views/products/_detail.html.erb
<div class="flex flex-col mt-8">
    <div class="-my-2 py-2 overflow-x-auto sm:-mx-6 sm:px-6 lg:-mx-8 lg:px-8">
        <div class="align-middle inline-block min-w-full shadow overflow-hidden sm:rounded-lg border-b border-gray-200">
            <div class="flex">
                <div class="w-1/2 px-6 py-3 border-b border-gray-200 bg-gray-50 text-left text-xs leading-4 font-medium text-gray-500 uppercase tracking-wider">Id</div>
                <div class="w-1/2 px-6 py-3 border-b border-gray-200 bg-gray-50 text-left text-xs leading-4 font-medium text-gray-500 uppercase tracking-wider">Description</div>
                <div class="w-1/2 px-6 py-3 border-b border-gray-200 bg-gray-50 text-left text-xs leading-4 font-medium text-gray-500 uppercase tracking-wider">Price</div>
                <div class="w-1/2 px-6 py-3 border-b border-gray-200 bg-gray-50 text-left text-xs leading-4 font-medium text-gray-500 uppercase tracking-wider">Status</div>
            </div>
            <div class="flex bg-white">
                <div class="w-1/2 px-6 py-4 whitespace-no-wrap border-b border-gray-200">
                    <div class="flex items-center">
                        <div class="ml-4">
                            <div class="text-sm leading-5 font-medium text-gray-900"><%= product.id %></div>
                        </div>
                    </div>
                </div>
                <div class="w-1/2 px-6 py-4 whitespace-no-wrap border-b border-gray-200">
                    <div class="flex items-center">
                        <div class="ml-4">
                            <div class="text-sm leading-5 text-gray-900"><%= product.description %></div>
                        </div>
                    </div>
                </div>
                <div class="w-1/2 px-6 py-4 whitespace-no-wrap border-b border-gray-200 text-sm leading-5 text-gray-500">
                    <%= product.price %>
                </div>
                <div class="w-1/2 px-6 py-4 whitespace-no-wrap border-b border-gray-200">
                    <span class="px-2 inline-flex text-xs leading-5 font-semibold rounded-full bg-green-100 text-green-800"><%= product.status %></span>
                </div>
            </div>
        </div>
    </div>
</div>

app/views/products/_form.html.erb
<div class="lg:col-span-2">

    <%= form_with(model: product, id: dom_id(product)) do |form| %>
      <% if product.errors.any? %>

        <div role="alert">
          <div class="bg-red-500 text-white font-bold rounded-t px-4 py-2">
            <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>
          </div>
          <div class="border border-t-0 border-red-400 rounded-b bg-red-100 px-4 py-3 text-red-700">
            <ul>
              <% product.errors.each do |error| %>
                <li><%= error.full_message %></li>
              <% end %>
            </ul>
          </div>
        </div>
      <% end %>

    <div class="grid grid-cols-6 gap-6">
        <div class="col-span-6 sm:col-span-3">
          <%= form.label :code, class: "w-full" %><br />
          <%= form.text_field :code, type:"text", class:"h-10 border mt-1 rounded px-4 bg-blue-50 focus:outline-none focus:ring-2 focus:ring-blue-600 focus:border-transparent", placeholder:"Code" %>
        </div>

        <div class="md:col-span-4">
          <%= form.label :description %><br />
          <%= form.text_field :description, type:"text", class:"h-10 border mt-1 rounded px-4 bg-blue-50 focus:outline-none focus:ring-2 focus:ring-blue-600 focus:border-transparent", placeholder:"Description" %>
        </div>

        <div class="md:col-span-3">
          <%= form.label :price %><br />
          <%= form.number_field :price, value: @product.price ? '%.2f' % @product.price : nil, min: 0, step: 0.01, class:"h-10 border mt-1 rounded px-4 bg-blue-50 focus:outline-none focus:ring-2 focus:ring-blue-600 focus:border-transparent", placeholder:"Price" %>
        </div>

        <div class="md:col-span-5">
          <%= form.label :category %>
          <div class="md:col-span-2">
            <%= form.collection_select :category_id,  Category.all, :id, :description, {prompt: true}, {class: "py-2 px-12 rounded-lg border-2 border-blue-300 mt-1 focus:outline-none focus:ring-2 focus:ring-blue-600 focus:border-transparent" } %>
          </div>
        </div>

        <div class="md:col-span-4 py-2 px-4 w-8 w-24 md:w-auto">
          <%= form.submit "Save", class:"bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-5 rounded" %>
          <%= link_to "Cancel", products_path, type:"button", class:"px-5 py-2 rounded-md text-sm font-medium border-0 focus:outline-none focus:ring transition text-white bg-red-500 hover:bg-red-600 active:bg-red-700 focus:ring-red-300" %>
        </div>
      </div>
    <% end %>
</div>

app/views/products/_product.html.erb
<%= turbo_frame_tag dom_id(product) do %>
   <div class="flex flex-col mt-8">
        <div class="-my-2 py-2 overflow-x-auto sm:-mx-6 sm:px-6 lg:-mx-8 lg:px-8">
            <div class="align-middle inline-block min-w-full shadow overflow-hidden sm:rounded-lg border-b border-gray-200">
                <div class="flex">
                    <div class="w-1/2 px-6 py-4 border-b border-gray-200 bg-gray-50 text-left text-xs leading-4 font-medium text-gray-500 uppercase tracking-wider">Id</div>
                    <div class="w-1/2 px-6 py-4 border-b border-gray-200 bg-gray-50 text-left text-xs leading-4 font-medium text-gray-500 uppercase tracking-wider">Code</div>
                    <div class="w-1/2 px-6 py-4 border-b border-gray-200 bg-gray-50 text-left text-xs leading-4 font-medium text-gray-500 uppercase tracking-wider">Description</div>
                    <div class="w-1/2 px-6 py-4 border-b border-gray-200 bg-gray-50 text-left text-xs leading-4 font-medium text-gray-500 uppercase tracking-wider">Category</div>
                    <div class="w-1/2 px-6 py-4 border-b border-gray-200 bg-gray-50 text-left text-xs leading-4 font-medium text-gray-500 uppercase tracking-wider">Price</div>
                    <div class="w-1/2 px-6 py-4 border-b border-gray-200 bg-gray-50 text-left text-xs leading-4 font-medium text-gray-500 uppercase tracking-wider">Status</div>
                    <div class="w-1/2 px-6 py-4 border-b border-gray-200 bg-gray-50 text-left text-xs leading-4 font-medium text-gray-500 uppercase tracking-wider">Actions</div>
                </div>
                <div class="flex bg-white">
                    <div class="w-1/2 px-6 py-4 whitespace-no-wrap border-b border-gray-200">
                        <div class="flex items-center">
                            <div class="ml-2">
                                <div class="text-sm leading-5 font-medium text-gray-900"><%= product.id %></div>
                            </div>
                        </div>
                    </div>
                       <div class="w-1/2 px-6 py-4 whitespace-no-wrap border-b border-gray-200">
                        <div class="flex items-center">
                            <div class="ml-2">
                                <div class="text-sm leading-5 font-medium text-gray-900"><%= product.code %></div>
                            </div>
                        </div>
                    </div>
                    <div class="w-1/2 px-6 py-4 whitespace-no-wrap border-b border-gray-200">
                        <div class="flex items-center">
                            <div class="ml-2">
                                <div class="text-sm leading-5 text-gray-900"><%= product.description %></div>
                            </div>
                        </div>
                    </div>
                       <div class="w-1/2 px-6 py-4 whitespace-no-wrap border-b border-gray-200">
                        <div class="flex items-center">
                            <div class="ml-2">
                                <div class="text-sm leading-5 text-gray-900"><%= product.category.description %></div>
                            </div>
                        </div>
                    </div>
                    <div class="w-1/2 px-6 py-4 whitespace-no-wrap border-b border-gray-200 text-sm leading-5 text-gray-500">
                        <%= sprintf('%.2f', product.price) %>
                    </div>
                    <div class="w-1/2 px-6 py-4 whitespace-no-wrap border-b border-gray-200">
                        <span class="px-2 inline-flex text-xs leading-5 font-semibold rounded-full bg-green-100 text-green-800"><%= product.status %></span>
                    </div>
                    <div class="w-1/2 px-6 py-4 whitespace-no-wrap text-left border-b border-gray-200 text-sm leading-5 font-medium">
                        <div class="flex items-center">
                            <div class="ml-2">
                                <%= link_to :edit, edit_product_path(product), class:"bg-blue-500 text-white active:bg-purple-600 font-bold uppercase text-xs px-4 py-2 rounded shadow hover:shadow-md outline-none focus:outline-none mr-1 mb-1 ease-linear transition-all duration-150" %>
                            </div>
                            <div class="ml-2">
                                <%= button_to :delete, product_path(product), method: :delete, class:"bg-red-500 text-white active:bg-purple-600 font-bold uppercase text-xs px-4 py-2 rounded shadow hover:shadow-md outline-none focus:outline-none mr-1 mb-1 ease-linear transition-all duration-150"  %>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
<% end %>

app/views/products/edit.html.erb
<%= turbo_frame_tag dom_id(@product) do %>
    <div class="container mx-auto px-6 py-8">
        <div class="mt-8"></div>
        <div class="flex flex-col mt-8">
            <div class="-my-2 py-2 overflow-x-auto sm:-mx-6 sm:px-6 lg:-mx-8 lg:px-8">
                <div class="bg-white rounded shadow-lg p-4 px-4 md:p-8 mb-4">
                    <div class="grid gap-4 gap-y-2 text-sm grid-cols-1 lg:grid-cols-3">
                        <div class="text-gray-600">
                            <p class="font-medium text-lg">Edit Product</p>
                            <p>Please fill out all the fields.</p>
                        </div>
                        <%= render 'form', product: @product %>
                    </div>
                    <%= render 'detail', product: @product %>
                </div>
            </div>
        </div>
        <div class="mt-8"></div>
    </div>
<% end %>

app/views/products/index.html.erb
<%= turbo_stream_from :products %>
<div class="container mx-auto px-6 py-8">
    <h3 class="text-gray-700 text-3xl font-medium">Product</h3>
    <div class="mt-8"></div>
    <div class="flex flex-col mt-8">
        <div class="-my-2 py-2 overflow-x-auto sm:-mx-6 sm:px-6 lg:-mx-8 lg:px-8">
            <div class="bg-white rounded shadow-lg p-4 px-4 md:p-8 mb-4">
                <div class="grid gap-4 gap-y-2 text-sm grid-cols-1 lg:grid-cols-3">
                   <div class="text-gray-600">
                        <p class="font-medium text-lg">Register Product</p>
                        <p>Please fill out all the fields.</p>
                    </div>
                    <%= turbo_frame_tag :product_form do %>
                        <%= render 'products/form', product: @product %>
                    <% end %>
                </div>
            </div>
        </div>
    </div>
    <%= turbo_frame_tag :products do %>
        <%= render @products %>
    <% end %>
    <div class="mt-8"></div>
</div>

app/views/products/new.html.erb
<div class="grid gap-4 gap-y-2 text-sm grid-cols-1 lg:grid-cols-3">
    <div class="text-gray-600">
        <p class="font-medium text-lg">Register Product</p>
        <p>Please fill out all the fields.</p>
    </div>
    <%= render 'form', product: @product %>
</div>

app/views/products/show.html.erb
<%= turbo_frame_tag dom_id(@product) do %>
  <div class="flex bg-white">
      <div class="w-1/2 px-6 py-4 whitespace-no-wrap border-b border-gray-200">
          <div class="flex items-center">
              <div class="ml-4">
                  <div class="text-sm leading-5 font-medium text-gray-900"><%= @product.id %></div>
              </div>
          </div>
      </div>
      <div class="w-1/2 px-6 py-4 whitespace-no-wrap border-b border-gray-200">
          <div class="flex items-center">
              <div class="ml-4">
                  <div class="text-sm leading-5 text-gray-900"><%= @product.description %></div>
              </div>
          </div>
      </div>
      <div class="w-1/2 px-6 py-4 whitespace-no-wrap border-b border-gray-200 text-sm leading-5 text-gray-500">
          <%= @product.price %>
      </div>
      <div class="w-1/2 px-6 py-4 whitespace-no-wrap border-b border-gray-200">
          <span class="px-2 inline-flex text-xs leading-5 font-semibold rounded-full bg-green-100 text-green-800"><%= @product.status %></span>
      </div>
      <div class="w-1/2 px-6 py-4 whitespace-no-wrap text-right border-b border-gray-200 text-sm leading-5 font-medium">
          <%= link_to :edit, edit_product_path(@product), class:"text-indigo-600 hover:text-indigo-900" %>
          <%= button_to :delete, product_path(@product), method: :delete %>
      </div>
  </div>
<% end %>